#!/bin/sh

COLOR='\033[1;33m'
NC='\033[0m' # No Color

if [[ $# -ne 2 ]] ; then
  echo -e "${COLOR}Usage: git-split.sh original copy${NC}"
  exit 10
fi

echo -e "${COLOR}> git diff-index --quiet HEAD" 
if ! git diff-index --quiet HEAD 
then
	echo -e "${COLOR}Det finns osparade förändringar, kommer göra stash${NC}"
	do_stash=1
fi

if [[ $do_stash -eq 1 ]]
then
	echo -e "${COLOR}> git stash save \"git-split-stash\"${NC}"
	git stash save "git-split-stash${NC}"
	stash_id=$(git stash list | grep git-split-stash | cut -d: -f1)
fi


echo -e "${COLOR}> git mv $1 $2${NC}"
git mv $1 $2

echo -e "${COLOR}> git commit -n -m \"Split history $1 to $2\"${NC}"
git commit -n -m "Split history $1 to $2${NC}"

echo -e "${COLOR}> REV=`git rev-parse HEAD`${NC}"
REV=`git rev-parse HEAD`

echo -e "${COLOR} > git reset --hard HEAD^${NC}"
git reset --hard HEAD^

echo -e "${COLOR}> git mv $1 temp${NC}"
git mv $1 temp

echo -e "${COLOR}> git commit -n -m \"Split history $1 to $2\"${NC}"
git commit -n -m "Split history $1 to $2${NC}"

echo -e "${COLOR}> git merge $REV${NC}"
git merge $REV

echo -e "${COLOR}> git commit -a -n -m \"Split history $1 to $2\"${NC}"
git commit -a -n -m "Split history $1 to $2${NC}"

echo -e "${COLOR}> git mv temp $1${NC}"
git mv temp $1

echo -e "${COLOR}> git commit -n -m \"Split history $1 to $2\"${NC}"
git commit -n -m "Split history $1 to $2${NC}"

if [[ $do_stash -eq 1 ]]
then
	echo -e "${COLOR}> git stash pop ${stash_id}${NC}"
	git stash pop ${stash_id} 
fi

echo -e "${COLOR}You are now Finnish${NC}"
